export function cardThemeTokens(isDark: boolean) {
    return isDark
        ? {
            heroBg: "from-navy-dark via-navy to-navy-light",
            contentBg: "from-navy-dark to-[#0a1628]",
            softBg: "bg-white/5",
            medBg: "bg-white/10",
            progressBg: "bg-white/10",
            text: "text-white",
            text80: "text-white/80",
            text70: "text-white/70",
            textMuted: "text-white/60",
            textSubtle: "text-white/50",
            textFaint: "text-white/40",
            textFainter: "text-white/35",
            textGhost: "text-white/30",
            textHint: "text-white/25",
            textDim: "text-white/20",
            accent: "text-saffron-light",
            accentBg: "bg-saffron/20",
            accentBorder: "border-saffron/30",
            closeBtn: "bg-white/10 hover:bg-white/20",
            closeIcon: "text-white",
            tabActive:
                "bg-white/10 text-saffron-light border-b-2 border-saffron",
            tabInactive: "text-white/50 hover:text-white/80",
            border: "border-white/10",
            genderBg: "bg-white/10 backdrop-blur",
            hoverBg: "hover:bg-white/10",
            tooltipStyle: {
                backgroundColor: "#1B3A6B",
                border: "none",
                borderRadius: 8,
                fontSize: 12,
                color: "#fff",
            },
            axisFill: "#ffffff50",
            gridStroke: "#ffffff15",
        }
        : {
            heroBg: "from-[#FFF8F0] via-white to-[#FFF3E6]",
            contentBg: "from-[#FFFDF8] to-white",
            softBg: "bg-[#f0ebe4]/60",
            medBg: "bg-[#e8e0d6]/60",
            progressBg: "bg-saffron/15",
            text: "text-[#1a1a2e]",
            text80: "text-[#2a2a3e]",
            text70: "text-[#3a3a4e]",
            textMuted: "text-[#4a4a5a]",
            textSubtle: "text-[#5a5a6a]",
            textFaint: "text-[#6B5A4E]",
            textFainter: "text-[#7a6a5e]",
            textGhost: "text-[#8a7a6e]",
            textHint: "text-[#9a8a7e]",
            textDim: "text-[#a09080]",
            accent: "text-[#c04800]",
            accentBg: "bg-saffron/12",
            accentBorder: "border-saffron/25",
            closeBtn: "bg-black/5 hover:bg-black/10",
            closeIcon: "text-[#3a3a4e]",
            tabActive:
                "bg-saffron/12 text-[#c04800] border-b-2 border-saffron",
            tabInactive: "text-[#6B5A4E] hover:text-[#2a2a3e]",
            border: "border-[#d4c4b4]/50",
            genderBg: "bg-saffron/8",
            hoverBg: "hover:bg-[#e8e0d6]/50",
            tooltipStyle: {
                backgroundColor: "#fffdf8",
                border: "1px solid rgba(180,150,120,0.3)",
                borderRadius: 8,
                fontSize: 12,
                color: "#1a1a2e",
            },
            axisFill: "#5a4a3e",
            gridStroke: "#00000015",
        };
}
